export enum DetailDataType {
  INPUT = 'INPUT',
  FILE = 'FILE',
  DATE = 'DATE',
  CHECKBOX = 'CHECKBOX',
  TEXTAREA = 'TEXTAREA',
  RADIO = 'RADIO',
  SELECT = 'SELECT',
  LIST = 'LIST',
  TABLE = 'TABLE',
  FORMGROUP = 'FORMGROUP',
  AUTOCOMPLETE = 'AUTOCOMPLETE',
  IMAGE = 'IMAGE'
}
